In [ ]:
#1. Import the NUMPY package under the name np.

In [8]:
import numpy as np


In [4]:
#2. Print the NUMPY version and the configuration.

In [11]:
print(np.__version__)
print(np.show_config())

1.23.1
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
a=np.random.rand(2,3,5)
a

array([[[0.29886649, 0.82880782, 0.88438422, 0.17378531, 0.58232105],
        [0.34351445, 0.8559811 , 0.01912274, 0.88041306, 0.67135806],
        [0.61322965, 0.47721399, 0.2369527 , 0.54584278, 0.05208137]],

       [[0.77080318, 0.56122876, 0.15563336, 0.34477193, 0.36058081],
        [0.24436303, 0.74318037, 0.42481426, 0.7763142 , 0.69119873],
        [0.0965505 , 0.9903197 , 0.21099604, 0.47003681, 0.34597261]]])

In [14]:
#4. Print a.
print(a)

[[[0.29886649 0.82880782 0.88438422 0.17378531 0.58232105]
  [0.34351445 0.8559811  0.01912274 0.88041306 0.67135806]
  [0.61322965 0.47721399 0.2369527  0.54584278 0.05208137]]

 [[0.77080318 0.56122876 0.15563336 0.34477193 0.36058081]
  [0.24436303 0.74318037 0.42481426 0.7763142  0.69119873]
  [0.0965505  0.9903197  0.21099604 0.47003681 0.34597261]]]


In [40]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b= np.ones((5,2,3))
#6. Print b.
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
#7. Do a and b have the same size? How do you prove that in Python code?
a==b

/var/folders/31/9bshvbnn2g16m9wz0gl028r00000gn/T/ipykernel_8470/2487780687.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a==b


False

In [42]:
#8. Are you able to add a and b? Why or why not?
#No because they have different structures

In [43]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c= b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [44]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d= a+c
d
#because they have the same structure now

array([[[1.29886649, 1.82880782, 1.88438422, 1.17378531, 1.58232105],
        [1.34351445, 1.8559811 , 1.01912274, 1.88041306, 1.67135806],
        [1.61322965, 1.47721399, 1.2369527 , 1.54584278, 1.05208137]],

       [[1.77080318, 1.56122876, 1.15563336, 1.34477193, 1.36058081],
        [1.24436303, 1.74318037, 1.42481426, 1.7763142 , 1.69119873],
        [1.0965505 , 1.9903197 , 1.21099604, 1.47003681, 1.34597261]]])

In [46]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)
# d elements are a+1

[[[0.29886649 0.82880782 0.88438422 0.17378531 0.58232105]
  [0.34351445 0.8559811  0.01912274 0.88041306 0.67135806]
  [0.61322965 0.47721399 0.2369527  0.54584278 0.05208137]]

 [[0.77080318 0.56122876 0.15563336 0.34477193 0.36058081]
  [0.24436303 0.74318037 0.42481426 0.7763142  0.69119873]
  [0.0965505  0.9903197  0.21099604 0.47003681 0.34597261]]]
[[[1.29886649 1.82880782 1.88438422 1.17378531 1.58232105]
  [1.34351445 1.8559811  1.01912274 1.88041306 1.67135806]
  [1.61322965 1.47721399 1.2369527  1.54584278 1.05208137]]

 [[1.77080318 1.56122876 1.15563336 1.34477193 1.36058081]
  [1.24436303 1.74318037 1.42481426 1.7763142  1.69119873]
  [1.0965505  1.9903197  1.21099604 1.47003681 1.34597261]]]


In [49]:
#12. Multiply a and c. Assign the result to e.
e=a*c
e
#13. Does e equal to a? Why or why not?
print(e)
print(a)
#Yes, because c is an array of ones

[[[0.29886649 0.82880782 0.88438422 0.17378531 0.58232105]
  [0.34351445 0.8559811  0.01912274 0.88041306 0.67135806]
  [0.61322965 0.47721399 0.2369527  0.54584278 0.05208137]]

 [[0.77080318 0.56122876 0.15563336 0.34477193 0.36058081]
  [0.24436303 0.74318037 0.42481426 0.7763142  0.69119873]
  [0.0965505  0.9903197  0.21099604 0.47003681 0.34597261]]]
[[[0.29886649 0.82880782 0.88438422 0.17378531 0.58232105]
  [0.34351445 0.8559811  0.01912274 0.88041306 0.67135806]
  [0.61322965 0.47721399 0.2369527  0.54584278 0.05208137]]

 [[0.77080318 0.56122876 0.15563336 0.34477193 0.36058081]
  [0.24436303 0.74318037 0.42481426 0.7763142  0.69119873]
  [0.0965505  0.9903197  0.21099604 0.47003681 0.34597261]]]


In [60]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

In [61]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty([2,3,5])
f

array([[[0.29886649, 0.82880782, 0.88438422, 0.17378531, 0.58232105],
        [0.34351445, 0.8559811 , 0.01912274, 0.88041306, 0.67135806],
        [0.61322965, 0.47721399, 0.2369527 , 0.54584278, 0.05208137]],

       [[0.77080318, 0.56122876, 0.15563336, 0.34477193, 0.36058081],
        [0.24436303, 0.74318037, 0.42481426, 0.7763142 , 0.69119873],
        [0.0965505 , 0.9903197 , 0.21099604, 0.47003681, 0.34597261]]])

In [71]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean,
#assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.

f=np.array([25 if d_min < x <d_mean else 75 if d_mean < x < d_max else 50 if x==d_mean else 0 if x==d_min else 100 for z in d for y in z for x in y]).reshape(2,3,5)
f    
    

array([[[ 25,  75,  75,  25,  75],
        [ 25,  75,   0,  75,  75],
        [ 75,  25,  25,  75,  25]],

       [[ 75,  75,  25,  25,  25],
        [ 25,  75,  25,  75,  75],
        [ 25, 100,  25,  25,  25]]])

In [72]:
#17. Print d and f. Do you have your expected f?
print(d)
print(f)

[[[1.29886649 1.82880782 1.88438422 1.17378531 1.58232105]
  [1.34351445 1.8559811  1.01912274 1.88041306 1.67135806]
  [1.61322965 1.47721399 1.2369527  1.54584278 1.05208137]]

 [[1.77080318 1.56122876 1.15563336 1.34477193 1.36058081]
  [1.24436303 1.74318037 1.42481426 1.7763142  1.69119873]
  [1.0965505  1.9903197  1.21099604 1.47003681 1.34597261]]]
[[[ 25  75  75  25  75]
  [ 25  75   0  75  75]
  [ 75  25  25  75  25]]

 [[ 75  75  25  25  25]
  [ 25  75  25  75  75]
  [ 25 100  25  25  25]]]


In [78]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
f_letters=np.array(["B" if d_min < x <d_mean else "D" if d_mean < x < d_max else "C" if x==d_mean else "A" if x==d_min else "E" for z in d for y in z for x in y]).reshape(2,3,5)
f_letters    

array([[['B', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'A', 'D', 'D'],
        ['D', 'B', 'B', 'D', 'B']],

       [['D', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'B', 'D', 'D'],
        ['B', 'E', 'B', 'B', 'B']]], dtype='<U1')